choco install git -y
choco install winrar -y
choco install tortoisegit -y
choco install jdk8 -y
choco install nodejs -y
choco install dotnetcore-sdk -y
choco install vscode -y
choco install slack -y
choco install android-sdk -y
choco install androidstudio -y
choco install dropbox -y
choco install googledrive -y